server:
  port: 8081
  context-path: /
spring:
  datasource:
    name: oauth2
    url: jdbc:mysql://127.0.0.1:3306/myself?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    # druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
mybatis:
    mapperLocations: classpath*:mybatis/mappings/**/*.xml
    typeAliasesPackage: cn.myself.platform.model.*.*
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



